---
Name: cwpconfig
After: 'cwp-core/*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
   - CWP\CWP\Extensions\CustomSiteConfig

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - CWP\CWP\Extensions\CwpSiteTreeExtension
  hide_pagetypes:
    - CWP\CWP\PageTypes\BasePage
    - CWP\CWP\PageTypes\BaseHomePage
    - CWP\CWP\PageTypes\DatedUpdatePage
    - CWP\CWP\PageTypes\DatedUpdateHolder

SilverStripe\Security\Member:
  title_format:
    columns:
      - FirstName
      - Surname
    sep: ' '
