name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Monday at 12:10pm UTC
  schedule:
    - cron: '10 12 * * 1'

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && startsWith(github.repository, 'silverstripe/')) || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
